spring:
  application:
    name: person

  data:
    mongodb:
      uri: ${DATABASE_URL}

project:
  client:
    person:
      zipcode:
        url: ${PROJECT_PERSON_ZIPCODE_URL}
        paths:
          get-zipcode: ws/{zip_code}/json
  person:
    minimum-age: ${PERSON_MINIMUM_AGE}